##
## EPITECH PROJECT, 2019
## makefile for tests
## File description:
##  by oriol
##

##
## EPITECH PROJECT, 2018
## by oriol
## File description:
## and
##


SRC	=	test.cpp		


NAME	=	unit_tests

all:
	g++ -o $(NAME)  $(SRC) --coverage -lcriterion -ldl
fclean:
	rm -rf *~ *# *.gcno *.gcda *unit_tests

